name: ppqm_interative
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipywidgets
  - jupyter
  - matplotlib
  - networkx
  - nglview
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - rdkit
  - rmsd
  - scipy
  - pip:
    - tqdm
    - rich
